name: Apple Platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  macos:
    name: macOS
    runs-on: macos-26
    permissions: {}
    steps:
      - uses: actions/checkout@v6
      - name: Build and test
        run: swift test

  ios:
    name: iOS
    runs-on: macos-26
    permissions: {}
    env:
      SCHEME: swift-tor-Package
    steps:
      - uses: actions/checkout@v6
      - name: Build for iOS
        run: |
          xcrun xcodebuild \
            -skipMacroValidation \
            -skipPackagePluginValidation \
            build \
            -scheme "$SCHEME" \
            -destination generic/platform=iOS
